const UPDATE_PAGE_COMPONENT = "UPDATE_PAGE_COMPONENT";
const ADD_PAGE_COMPONENT = "ADD_PAGE_COMPONENT";
const UPDATE_COMPONENT_DATA_BY_ID = "UPDATE_COMPONENT_DATA_BY_ID";
const TRIGGER_COMPONENT_PROPS_CHANGE = "TRIGGER_COMPONENT_PROPS_CHANGE";
const TRIGGER_COMPONENT_CONFIG_CHANGE = "TRIGGER_COMPONENT_CONFIG_CHANGE";
const TRIGGER_OVERRIDE_TEMPLATE = "TRIGGER_OVERRIDE_TEMPLATE";
const TRIGGER_COLLECTION_ACTION = "TRIGGER_COLLECTION_ACTION";
const REFRESH_CONFIG = "REFRESH_CONFIG";
const CHANGE_IMAGE = "CHANGE_IMAGE";

export {
    UPDATE_PAGE_COMPONENT,
    ADD_PAGE_COMPONENT,
    UPDATE_COMPONENT_DATA_BY_ID,
    TRIGGER_COMPONENT_PROPS_CHANGE,
    TRIGGER_COMPONENT_CONFIG_CHANGE,
    TRIGGER_OVERRIDE_TEMPLATE,
    TRIGGER_COLLECTION_ACTION,
    REFRESH_CONFIG,
    CHANGE_IMAGE,
};
